# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_is_dataset', models.BooleanField(default=False)),
                ('dataset_class', models.CharField(max_length=40, null=True)),
                ('message', models.TextField(default='', null=True)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('doctors', models.ManyToManyField(through='ekg.Affiliation', to='ekg.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg.Patient'),
        ),
        migrations.AddField(
            model_name='history',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg.Hospital'),
        ),
        migrations.AddField(
            model_name='history',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg.Doctor'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg.Doctor'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg.Hospital'),
        ),
    ]
