# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekg', '0002_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ekg.Hospital'),
        ),
        migrations.AlterField(
            model_name='history',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ekg.Doctor'),
        ),
    ]
